/* ============================================
   SCHEMA.TS — All DrizzleORM Table Definitions
   Chatbot Polimdo — PostgreSQL
   ============================================ */

import {
  pgTable,
  serial,
  text,
  integer,
  boolean,
  timestamp,
  json,
  real,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

// ══════════════════════════════════════════════
// BETTER AUTH TABLES
// (Generated by: npx auth@latest generate)
// ══════════════════════════════════════════════

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// ══════════════════════════════════════════════
// APPLICATION TABLES — Campus Content
// ══════════════════════════════════════════════

/** Campus general info (single row) */
export const kampusInfo = pgTable("kampus_info", {
  id: serial("id").primaryKey(),
  nama: text("nama").notNull(),
  singkatan: text("singkatan"),
  alamat: text("alamat"),
  telepon: text("telepon"),
  email: text("email"),
  website: text("website"),
  whatsapp: text("whatsapp"),
  mapsUrl: text("maps_url"),
  visi: text("visi"),
  misi: json("misi").$type<string[]>(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

/** Study Programs / Departments */
export const jurusan = pgTable("jurusan", {
  id: serial("id").primaryKey(),
  nama: text("nama").notNull(),
  jenjang: text("jenjang").notNull(),
  akreditasi: text("akreditasi").default("B"),
  icon: text("icon").default("🎓"),
  biaya: text("biaya"),
  deskripsi: text("deskripsi"),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

/** Admission Paths */
export const pendaftaran = pgTable("pendaftaran", {
  id: serial("id").primaryKey(),
  jalur: text("jalur").notNull(),
  nama: text("nama").notNull(),
  periode: text("periode"),
  syarat: text("syarat"),
  biayaPendaftaran: text("biaya_pendaftaran"),
  icon: text("icon").default("📝"),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

/** Scholarships */
export const beasiswa = pgTable("beasiswa", {
  id: serial("id").primaryKey(),
  nama: text("nama").notNull(),
  deskripsi: text("deskripsi"),
  icon: text("icon").default("🏅"),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

/** Facilities */
export const fasilitas = pgTable("fasilitas", {
  id: serial("id").primaryKey(),
  nama: text("nama").notNull(),
  icon: text("icon").default("🏫"),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

/** FAQ */
export const faq = pgTable("faq", {
  id: serial("id").primaryKey(),
  pertanyaan: text("pertanyaan").notNull(),
  jawaban: text("jawaban").notNull(),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

/** Contact info */
export const kontak = pgTable("kontak", {
  id: serial("id").primaryKey(),
  tipe: text("tipe").notNull(),
  label: text("label").notNull(),
  value: text("value").notNull(),
  url: text("url"),
  icon: text("icon").default("📞"),
  sortOrder: integer("sort_order").default(0),
  isActive: boolean("is_active").default(true),
});

// ══════════════════════════════════════════════
// CHATBOT INTELLIGENCE
// ══════════════════════════════════════════════

/** Intent definitions for keyword matching */
export const intents = pgTable("intents", {
  id: serial("id").primaryKey(),
  name: text("name").notNull().unique(),
  keywords: json("keywords").$type<string[]>().notNull(),
  exactMatch: json("exact_match").$type<string[]>(),
  responseType: text("response_type").notNull().default("text"),
  responseTemplate: text("response_template"),
  introText: text("intro_text"),
  dataSource: text("data_source"),
  isActive: boolean("is_active").default(true),
  priority: integer("priority").default(0),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// ══════════════════════════════════════════════
// ANALYTICS — Chat Sessions & Messages
// ══════════════════════════════════════════════

/** Chat sessions */
export const chatSessions = pgTable(
  "chat_sessions",
  {
    id: serial("id").primaryKey(),
    sessionUuid: text("session_uuid").notNull().unique(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    startedAt: timestamp("started_at").defaultNow(),
    lastActivity: timestamp("last_activity").defaultNow(),
  },
  (table) => ({
    uuidIdx: uniqueIndex("session_uuid_idx").on(table.sessionUuid),
    startedIdx: index("session_started_idx").on(table.startedAt),
  })
);

/** Chat message log */
export const chatMessages = pgTable(
  "chat_messages",
  {
    id: serial("id").primaryKey(),
    sessionId: integer("session_id")
      .notNull()
      .references(() => chatSessions.id, { onDelete: "cascade" }),
    sender: text("sender").notNull(), // 'user' | 'bot'
    message: text("message").notNull(),
    matchedIntent: text("matched_intent"),
    confidenceScore: real("confidence_score"),
    responseType: text("response_type"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (table) => ({
    sessionIdx: index("msg_session_idx").on(table.sessionId),
    intentIdx: index("msg_intent_idx").on(table.matchedIntent),
    createdIdx: index("msg_created_idx").on(table.createdAt),
  })
);

// ══════════════════════════════════════════════
// TYPE EXPORTS
// ══════════════════════════════════════════════

export type Jurusan = typeof jurusan.$inferSelect;
export type NewJurusan = typeof jurusan.$inferInsert;
export type Pendaftaran = typeof pendaftaran.$inferSelect;
export type NewPendaftaran = typeof pendaftaran.$inferInsert;
export type Beasiswa = typeof beasiswa.$inferSelect;
export type NewBeasiswa = typeof beasiswa.$inferInsert;
export type Fasilitas = typeof fasilitas.$inferSelect;
export type NewFasilitas = typeof fasilitas.$inferInsert;
export type FAQ = typeof faq.$inferSelect;
export type NewFAQ = typeof faq.$inferInsert;
export type Kontak = typeof kontak.$inferSelect;
export type NewKontak = typeof kontak.$inferInsert;
export type Intent = typeof intents.$inferSelect;
export type NewIntent = typeof intents.$inferInsert;
export type ChatSession = typeof chatSessions.$inferSelect;
export type ChatMessage = typeof chatMessages.$inferSelect;
